### ISSUE TITLE
Some mangas from MangaTown are unsearchable and unreadable

### ISSUE THREAD

**Issue by BrokenGale** [nv95/Kotatsu#10]
Some mangas are becoming becoming unreadable and unsearchable.
When trying to view manga from favorites or history, a generic "An error has occurred" message pops up.

Mangas include:
Legendary Moonlight Sculptor
Holy Guardian Tiger
Monster Duchess and Contract Princess
Tonikaku Kawaii
Second Life Ranker
Chitra (Confirmed unsearchable)
I am a Child of this House

**Comment by nv95** [comment]
Fixed
