### ISSUE TITLE
Нужен ли Discord сервер?

### ISSUE THREAD

**Issue by ztimms73** [nv95/Kotatsu#105]
Пришла идея создать сервер Discord для более удобной коммуникации с пользователями приложения, да и обсуждать некоторые моменты там, чем например в тикетах. И самый главный вопрос - полезно ли будет?)

![image](https://user-images.githubusercontent.com/61558546/155409021-08532343-1563-4484-8f63-463124e27820.png)

**Comment by ParTy-Play-go** [comment]
Я могу ботов сделац)

**Comment by ztimms73** [comment]
Пока есть такой бот, который берёт из анилиста тайтлы, не только манги, но и аниме и прочего формата контента. https://github.com/ztimms73/Kotatsu-bot

https://discord.gg/NNJ5RgVBC5

**Comment by ParTy-Play-go** [comment]
https://dsc.gg/shimoro бот для просмотра аниме

**Comment by ztimms73** [comment]
Думаю, это слишком. Я думаю, будет достаточно двух ботов: Carl - автомодератора, к которому можно будет приделать триггеры и кастомные команды и Kotatsu-bot: для быстрого поиска тайтлов в Anilist

**Comment by ztimms73** [comment]
Думаю, тикет можно закрыть. Предложения по улучшению сервера можно оставить в канале #server-suggestions
