### ISSUE TITLE
add support for blocking screenshots being taken

### ISSUE THREAD

**Issue by grrrrr** [nv95/Kotatsu#114]
I am aware that this is not a perfect privacy solution and there are ways around it but it would be useful to have Kotatsu block the ability to take screenshots.

While the risks / concerns of someone remotely taking a screenshot of Kotatsu on your phone are low, but when you switch between apps on Android it will display a snapshot of the last screen of each open app on your phone.

With screenshots blocked, switching apps would result in you seeing Kotatsu is open but not seeing the screen and given some of the content of various manga could save potential embarrassment or just stop shoulder surfers (e.g. on public transport).

Some apps that do that have this option if examples/comparison is needed

  * Signal (allows toggling screenshot capture on or off)
  * Protonmail (always blocked)
  * Aegis (allows toggling screenshot capture on or off)

**Comment by nv95** [comment]
Implemented as option only for reader. I think it is useless for lists

**Comment by grrrrr** [comment]
@nv95 that's great thank you for quick solution! while blocking on all screens would be perfect this is a good compromise :)

**Comment by grrrrr** [comment]
@nv95 one other place that would be useful to have this would be on the password setup and entry screen, if possible.
