### ISSUE TITLE
Web page refreshes when rotating screen

### ISSUE THREAD

**Issue by mmc20520** [nv95/Kotatsu#119]
The internal webview refreshes the web content after device orientation change, then I need to manually restore webview state. Would you be able to store webview states in the program?

Before rotation:
![pic13](https://user-images.githubusercontent.com/100833575/156735909-29faac32-6daa-4d69-9c92-3672feb517e3.png)

After rotation:

![pic14](https://user-images.githubusercontent.com/100833575/156735940-8254f74b-a6a6-44bb-9b50-8f1abe5368f0.png)

**Comment by nv95** [comment]
Available in #130
