### ISSUE TITLE
English manga sources

### ISSUE THREAD

**Issue by GoluLiliput** [nv95/Kotatsu#14]
Is there any English manga sources in the app? I couldn't find any... Please help

**Comment by nv95** [comment]
MangaTown is available for now

**Comment by JotaRodriguez4** [comment]
Is there any Spanish manga sources in the app? I couldn't find any.
Some suggestions.
https://lectormanga.com/
https://lectortmo.com/
https://es.ninemanga.com/
Please help!

**Comment by ztimms73** [comment]
> Is there any Spanish manga sources in the app? I couldn't find any.

No, there are no Spanish-language manga sources in the app, but I can try to add one of the suggested ones when I have free time.

**Comment by JotaRodriguez4** [comment]
> > Is there any Spanish manga sources in the app? I couldn't find any.
> 
> No, there are no Spanish-language manga sources in the app, but I can try to add one of the suggested ones when I have free time.

Thank you!✨

**Comment by nv95** [comment]
@ztimms73 looks like ninemanga.com has multiple languages, so, we can implement multiple sources with just different domains

**Comment by ztimms73** [comment]
> @ztimms73 looks like ninemanga.com has multiple languages, so, we can implement multiple sources with just different domains.
> 
> upd: I will implement it

I had an idea to make the main English source, and in the domain settings, you could change it, for example, to es., ru., fr., etc.

**Comment by nv95** [comment]
> in the domain settings

Users may not know about this feature. I think it will be better to create different sources with a single base implementation

**Comment by nv95** [comment]
Closed as a duplicate of #77
