### ISSUE TITLE
Webtoon mode by default

### ISSUE THREAD

**Issue by YeiserDeveloper** [nv95/Kotatsu#142]
that we can configure a view mode and be permanent

**Comment by nv95** [comment]
What do you mean under the 'website mode'?

**Comment by YeiserDeveloper** [comment]
![Screenshot_20220418-080850_Kotatsu.jpg](https://user-images.githubusercontent.com/97372908/163806209-f35d021f-1bdd-4718-bd13-233ca6e3e6ed.jpg)

**Comment by YeiserDeveloper** [comment]
![Screenshot_20220418-080850_Kotatsu.jpg](https://user-images.githubusercontent.com/97372908/163806433-1a2e5bf5-9973-4f5e-9120-7fc08fd0bdf1.jpg)

**Comment by YeiserDeveloper** [comment]
> What do you mean under the 'website mode'?

![Screenshot_20220418-080850_Kotatsu.jpg](https://user-images.githubusercontent.com/97372908/163806586-334d2867-09d6-41e3-afc4-475868fc7a0a.jpg)

**Comment by YeiserDeveloper** [comment]
Every time you enter a manga you must put it in that mode.

**Comment by YeiserDeveloper** [comment]
Thanks
