### ISSUE TITLE
MangaDex and "Save" manga related issues

### ISSUE THREAD

**Issue by Zehra** [nv95/Kotatsu#143]
**Issues/bugs**
* Save manga may include chapters in other languages. (MangaDex)
* Save manga may not include chapters in some languages. (MangaDex)
(Example: manga offered in languages a and b and both are included in save manga. Manga is offered in languages a, b and c, but only a is included, despite b being the preference, but seems to vary depending on manga.)
* Not all chapters visible in MangaDex in some mangas. (80+ chapters online in language a, but only around 20 visible.)

**Comment by nv95** [comment]
It will be nice if you provide some details/screenshots/etc

**Comment by Zehra** [comment]
(Note: Items in bullet points and in bold are manga titles.)
Examples: 
**Language selection for chapters?**
* **Metal Heart** `39 chapters in English, 27 in Portuguese.` (It says to save all 66 chapters.)
![metal_heart_Kotatsu](https://user-images.githubusercontent.com/22282963/163727294-be8fe262-96f3-4ec3-a695-cac2679a0795.jpg)

**Incorrect/inconsistent chapter count/visibility**
* **Tomo-chan wa Onnna no ko!** (96 chapters listed, only 10 listed in English.)
![tomo-chan_Kotatsu](https://user-images.githubusercontent.com/22282963/163727504-24db0976-ead5-433e-893c-f0f7b3210ad6.jpg)
![tomo-chan-chapters_Kotatsu](https://user-images.githubusercontent.com/22282963/163727509-fdfffd72-f73f-4377-8ddd-d13e84ba9db5.jpg)
![tomo-chan_Browser](https://user-images.githubusercontent.com/22282963/163727513-2b07779f-6557-4ba3-a6ab-c0c7936e5e1b.jpg)

* **Denpa Kyoushi** (96 chapters listed, only 48 listed in English.)
![denpa_Kotatsu](https://user-images.githubusercontent.com/22282963/163728474-4df6738f-688f-49cf-b48a-d955044d77ca.jpg)
![denpa_chapters_Kotatsu](https://user-images.githubusercontent.com/22282963/163728478-6ca2754c-7bb2-4b7e-8cba-a7e5530251b3.jpg)
![denpa_Browser](https://user-images.githubusercontent.com/22282963/163728481-dd820e0b-0f8b-4b97-9b3b-c6f6d2d41ac4.jpg)

**Save manga errors/bugs**
* **Can You Still Love Your Boyfriend When He Becomes a Woman?**
![2chapters_Kotatsu](https://user-images.githubusercontent.com/22282963/163728603-4473c566-8d08-43ac-84b9-37cccae07014.jpg)
![2chapters_in_saved_manga_Kotatsu](https://user-images.githubusercontent.com/22282963/163728607-e3bdec41-537c-4521-8a87-fbaa34daf9b5.jpg)
(Downloads different languages as a single chapter.)
* **Okitara Onnanoko no Karada ni Natteta Hanashi**
![chapters_Kotatsu](https://user-images.githubusercontent.com/22282963/163728698-79e5cf00-5ede-446c-9352-e6aa369dd884.jpg)
![chapters_missing_Kotatsu](https://user-images.githubusercontent.com/22282963/163728703-0bf59e24-d282-43b5-82ab-87502b957579.jpg)
(Selects a single language, but unable to select others?)

**Comment by Emerald-glitch** [comment]
I think my problem is also somewhat related, the thing is, the app has two download threads, but if both of them are used, the chapters downloaded end up corrupted, incomplete pages, missing pages, exchange of pages between the mangas. 

Maybe an option to limit download thread will work.

**Comment by nv95** [comment]
Should be fixed now

**Comment by Zehra** [comment]
Everything works, although I can't verify on the chapter listing, unless I'm missing something?

**Comment by Zehra** [comment]
Closing issue, as it's parser specific.
