### ISSUE TITLE
Disable automatic app update checks and notifications

### ISSUE THREAD

**Issue by yephny** [nv95/Kotatsu#147]
For people who download and update the app using an F-Droid client, the app [update checks](https://i.imgur.com/6jTXiQV.png) that Kotatsu does are useless. The app's signature is different from the F-Droid version, so it wouldn't be possible to update it this way.

What I recommend is that you add an option in settings where we can turn on/off "check for app updates".

**Comment by nv95** [comment]
F-droid version should not check for updates. Looks like a bug

**Comment by nv95** [comment]
Fixed
