### ISSUE TITLE
Wrong Search keyboard

### ISSUE THREAD

**Issue by hutiwephy** [nv95/Kotatsu#150]
The current search keyboard as the emoji panel button instead of the return or search button

![Screenshot_20220419-125233_Kotatsu.png](https://user-images.githubusercontent.com/68164156/163997604-4b5dfe07-0881-4c26-b667-e04e6205fa80.png)

**Comment by hutiwephy** [comment]
search is not displaying results even with a wired keyboard

**Comment by ztimms73** [comment]
> search is not displaying results

Looks like a problem with the source. Or is there something I don't understand?

Can you provide your keyboard app title (looks like GBoard) and version?

**Comment by nv95** [comment]
I think search results are not displaying because of is impossible to click "search" on this keyboard

**Comment by ztimms73** [comment]
Ah, right

**Comment by nv95** [comment]
@hutiwephy can you check it? Should be fixed in v3.2

**Comment by hutiwephy** [comment]
Thanks it's working
