### ISSUE TITLE
Wrong file extension for page downloads

### ISSUE THREAD

**Issue by yephny** [nv95/Kotatsu#151]
Foe some manga, when you save a page, it gets saved with .html or no extensions. Changing it back to .png manually solves the issue. You can see it in action when saving a page from "Grand Blue".

**Comment by yephny** [comment]
@nv95 MangaTown, any chapter will do, try the first page of Chapter 1.

**Comment by EdgE790** [comment]
It seems the issue still persists. Now no extension is added at all. 
My issue is with ComicK source.
