### ISSUE TITLE
Styling Genres Position

### ISSUE THREAD

**Issue by OshekharO** [nv95/Kotatsu#156]
### Describe your suggested feature

It should look like synonyms :
![Screenshot_20220425-125603_Saikou](https://user-images.githubusercontent.com/95137948/165040587-605639ef-9227-489c-a6f7-98b3810fc45e.png)

Refrence taken from saikou

### Other details

It will make the ui look more pleasant

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [parsers repository](https://github.com/nv95/kotatsu-parsers/issues/new).
- [X] I have updated the app to version **[3.2](https://github.com/nv95/Kotatsu/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by OshekharO** [comment]
Well I don't think it has much effect but ya it will make the app look much better

**Comment by ztimms73** [comment]
> ( Modern UI )

We have it, yeah :)
I'm closing this ticket, because it can mess up the UX a bit

**Comment by brahmkshatriya** [comment]
> I think horizontal scroll inside a ViewPager is not a good idea

That's where you disable horizontal scroll for viewpager

Though, overriding the scrollview's on scroll method or something can overcome the problem
