### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by EdgE790** [nv95/Kotatsu#16]
I don't know if it's hard, but I found the previous project (OpenManga) here.
Is it possible to create a new release for kotatsu?

**Comment by nv95** [comment]
It available here: https://animanga.efreakbnc.net/fdroid/repo?fingerprint=65F5EF1A9AE6FD7739FFB62E7C7021775198501780312BE1B782D4CA9FE07957

**Comment by nv95** [comment]
And also coming soon in official repository

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7188

**Comment by IzzySoft** [comment]
> And also coming soon in official repository

But only if you respond there to fix open issues, @nv95 :wink:

So are you going to? Maybe you've missed the pings from there?

**Comment by nv95** [comment]
All is ok)

I do it after next release

**Comment by IzzySoft** [comment]
Just stumbled on your MR again and see there's a new release here, cool! Is there already an ETA for picking up the MR? I guess you'll want to do another release first?

**Comment by nv95** [comment]
At end of February

**Comment by nv95** [comment]
I'm sorry, release is reposing due to a lack of time(
There are some bugs needs to be fixed

**Comment by IzzySoft** [comment]
Thanks for the heads-up, @nv95 – I've added a note to the RFP (resetting the "inactivity timer"). Crossing fingers you find time soon and fixes are easy! Said "timer" will "ring" again in about a months. Whoever is first will ping then again – unless the RFP was updated before that :smile:

Best luck!

**Comment by nv95** [comment]
Merge request to f-droid data repository is ready for merging and waiting for review
