### ISSUE TITLE
Inbuilt proxy for ISP Block BYPASS

### ISSUE THREAD

**Issue by OshekharO** [nv95/Kotatsu#161]
### Describe your suggested feature

It should be like this: 
![Screenshot_20220502-205841_CloudStream Beta](https://user-images.githubusercontent.com/95137948/166261557-9a361ab5-d675-40cb-b1d5-b2e8aa53b633.png)

To bypass issues like this:
![Screenshot_20220502-210045_Kotatsu](https://user-images.githubusercontent.com/95137948/166261728-106496ce-a44f-4ec5-8844-bdcd89e2e908.png)

### Other details

Reference taken from CloudStream 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [parsers repository](https://github.com/nv95/kotatsu-parsers/issues/new).
- [X] I have updated the app to version **[3.2](https://github.com/nv95/Kotatsu/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ztimms73** [comment]
Hm, I think this is useful feature!

**Comment by yephny** [comment]
Proxy would work when your ISP has the IP addresses of the website you want to access blocked. Though, it would be too costly to implement in the app, so you'd need an external proxy server, like VPN providers.
I can infer from the first screenshot that the feature you are requesting is DNS encryption to mitigate restrictions set by your DNS provider.

**Comment by OshekharO** [comment]
Thx
