### ISSUE TITLE
Не загружается манга с ридманги/минтманги

### ISSUE THREAD

**Issue by npocToTaHkucT** [nv95/Kotatsu#169]
### Steps to reproduce

1. Зайти в каталог Readmanga/Mintmanga
2. Открыть превью, нажать читать/продолжить

### Expected behavior

Должна открыться манга/манхва

### Actual behavior

Возникает сообщение "Произошла ошибка - Index 1 out of range [0..0)"

### Kotatsu version

3.2.2

### Android version

Android 11

### Device

Samsung M21

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [parsers repository](https://github.com/nv95/kotatsu-parsers/issues/new).
- [X] I have updated the app to version **[3.2.2](https://github.com/nv95/Kotatsu/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by npocToTaHkucT** [comment]
Хотел бы подметить, что ошибка появилась с выходом 3.2.2

**Comment by ztimms73** [comment]
> If this is an issue with a source, I should be opening an issue in the **parsers** repository.

Неправильный репозиторий.

Проблема известна, в следующей версии будет исправлено.

**Comment by nv95** [comment]
Already fixed in #170, release is coming soon
