### ISSUE TITLE
Manga source: magaread.org

### ISSUE THREAD

**Issue by Androkai** [nv95/Kotatsu#17]
Hey guys,

If possible, may I ask you to add [magaread.org](https://www.mangaread.org/) as a better source for English manga and webtoons compared to magatown.com? Would love to read *The Beginning After the End* and *Solo Leveling* in English with the app.

Keep up the great work!

**Comment by nv95** [comment]
This site is currently unavailable(

**Comment by nv95** [comment]
Available since v1.0
