### ISSUE TITLE
Error 403 mangalib.me

### ISSUE THREAD

**Issue by Thadorior** [nv95/Kotatsu#18]
Не открывается манга с сайта mangalib.me, хотя по ссылке из приложения в браузере главы работаю
![Screenshot_2020-12-14-00-11-44-923_org koitharu kotatsu](https://user-images.githubusercontent.com/31935008/102024210-bde71880-3da1-11eb-814b-8a7d6106ea76.jpg)

**Comment by nv95** [comment]
Это из-за CloudFlare. Фикс будет доступен в следующем релизе

**Comment by nv95** [comment]
Fixed in v1.0
