### ISSUE TITLE
Ошибка при открытии манги

### ISSUE THREAD

**Issue by San4ito** [nv95/Kotatsu#2]
При открытии практически любой манги возникает ошибка:
![Screenshot_20200329-163830](https://user-images.githubusercontent.com/24568377/77850805-8f0e1f80-71dd-11ea-9827-e67a586efe91.png)

Телефон с Android 10
Приложение версии 0.1.2

**Comment by nv95** [comment]
Уже есть исправленная 0.1.3

**Comment by San4ito** [comment]
Проверил, работает!☺️
Тогда ошибку можно закрывать!
