### ISSUE TITLE
manhua scrolling is bugged

### ISSUE THREAD

**Issue by iliabeluch** [nv95/Kotatsu#20]
The bug was there for ages. It was in OpenManga too.

When you read manhua with long vertical images in scroll mode (manhua mode) it often split screen in two. Where on top part remains previous image and on bottom part appears next image. And now both images can be scrolled separately from each other. Bottom image always appears not from the top of it - it starts from the middle, so you can scroll it both ways - up and down.

To resolve the bug you need to scroll bottom image to the beginning of it and a little bit mote. In this case separator moves away from the screen and you again can see and scroll only one image.

I think this bug is somehow caused by poor connectivity to manga server. When you reading slowly the connection is getting lost and when you reach the end of current image, connection resumes and this bug appears.

There is another thing - sometimes when you reach the end, it scrolls current chapter back to the beginning. Occurs in scroll mode and not only with source with big long images. It's very irritating. And it seems that in is caused by reconnection too.

Both bugs does not appear when you scroll pages fast. When you read on normal speed it appears every 3-5 chapters. You can reproduce it on any manhua with long pages, on this one for example: https://readmanga.live/magiia_vernuvshegosia_doljna_byt_osobennoi

https://imgur.com/a/TPU4Ibz - screenshots

**Comment by DeadlyPresence** [comment]
According to commit e7e9c5fe9ff9fa992ea2f5fc6ecc4ac62b7850e9 overlapping content has been fixed, but the problem is still present and a possibility to manually fix the position now is locked, which means is impossible to normally read in manhua mode.

**Comment by nv95** [comment]
Cannot reproduce, but it may be related to the issue #7

**Comment by DeadlyPresence** [comment]
I can reproduce this bug, but how can I make a dump for you to inspect this bug?

**Comment by iliabeluch** [comment]
A lot of updates were deployed, so I have not experienced this bug anymore.
Instead there is new similar bug: sometimes one of the long manhua images appears shifted to the right with white 25% space to the left of it. Problem fixed by changing screen orientation back and forth. The downside of this fix is that it resets position on the current page and you need to scroll forth to old reading position.

**Comment by nv95** [comment]
Please, open a new issue if any troubles are become
