### ISSUE TITLE
Mangalib solve captcha not working

### ISSUE THREAD

**Issue by gaiththewolf** [nv95/Kotatsu#21]
Hi,

Sometimes solve captcha not working in mangalib source, Sometimes work but sometimes not working just chowing box for while and gone

**Comment by gaiththewolf** [comment]
i think it will be resolved by adding `it.value.isNotEmpty()` in **CloudFlareClient.kt** on `checkClearance()` like this :

```
private fun checkClearance() {
  val cookies = cookieJar.loadForRequest(targetUrl.toHttpUrl())
  if (cookies.any { it.name == CF_CLEARANCE && it.value.isNotEmpty() }) {
	  callback.onCheckPassed()
  }
}
```

**Comment by nv95** [comment]
Thanks! Looks like AndroidCookieJar has a bug, I`ll fix it

**Comment by gaiththewolf** [comment]
thanks, works fine.
