### ISSUE TITLE
Ошибка при открытии манги

### ISSUE THREAD

**Issue by Andrey21ru** [nv95/Kotatsu#3]
![Screenshot_20200330-092703](https://user-images.githubusercontent.com/45811476/77882526-cd512080-7269-11ea-885c-100dbbb4ede3.png)
Версия андроид 7.0
Версия приложения 0.1.3

**Comment by nv95** [comment]
Как можно воспроизвести?

**Comment by Andrey21ru** [comment]
Это ошибка проявляется только на ReadManga-е, при выборе некоторой манги

**Comment by Andrey21ru** [comment]
При попытке открыть мангу которую ещё не читал

**Comment by Andrey21ru** [comment]
При попытке начать чтения манги, которую ещё не читали на ReadManga
Так будет точнее

**Comment by nv95** [comment]
Точно воспроизводится в 0.1.3?
Такой баг был в 0.1.2 и он уже исправлен

**Comment by Andrey21ru** [comment]
Да, точно

**Comment by Andrey21ru** [comment]
Скачал 0.1.3 на планшет, и там та же ошибка

**Comment by Andrey21ru** [comment]
![Screenshot_20200330-164254](https://user-images.githubusercontent.com/45811476/77919402-cea03e80-72a5-11ea-9d5b-9b9ba5ba8b00.png)

**Comment by nv95** [comment]
Ок, разберусь

**Comment by Andrey21ru** [comment]
Буду ждать исправления

**Comment by nv95** [comment]
Done

**Comment by Andrey21ru** [comment]
Thank you
