### ISSUE TITLE
App Crash while opening Mangalib and Hentalib

### ISSUE THREAD

**Issue by GoluLiliput** [nv95/Kotatsu#37]
The app crashes and shows this error msg...
![Screenshot_2021-06-29-07-23-15-274_org.koitharu.kotatsu.jpg](https://user-images.githubusercontent.com/60719832/123725093-206db500-d8ab-11eb-953a-d4a7053ff14c.jpg)

Also app crash with a msg while opening HentaiLib too
![Screenshot_2021-06-29-07-26-47-117_org.koitharu.kotatsu.jpg](https://user-images.githubusercontent.com/60719832/123725328-8f4b0e00-d8ab-11eb-9747-8b6234d7750a.jpg)

**Comment by GoluLiliput** [comment]
I guess this is happening because the websites themselves are down. These sources can be removed and replaced.

**Comment by nv95** [comment]
Fixed in v1.1.2
