### ISSUE TITLE
Небольшой баг при открытии манги

### ISSUE THREAD

**Issue by San4ito** [nv95/Kotatsu#4]
При открытии манги (поиск через Readmanga) возникает ошибка: 
![image](https://user-images.githubusercontent.com/24568377/81268668-e9a66100-9050-11ea-84d1-c15ddd8b2598.png)
Судя по ссылке, приложение пытается получить данные с сайта Readmanga, хотя на сайте такой манги нет (возможно, была удалена). Но если открыть в браузере, то манга располагается на Mintmanga: 
![image](https://user-images.githubusercontent.com/24568377/81269310-cb8d3080-9051-11ea-9223-6e649067f20d.png)
Если изначально искать на Mintmanga, то проблем не возникает, всё открывается.

**Comment by nv95** [comment]
Fixed, coming soon in next release
