### ISSUE TITLE
Need of the pdf

### ISSUE THREAD

**Issue by pixelroll** [nv95/Kotatsu#46]
Hello,
I am currently reading several webtoon translated only in pdf.
I read them on google drive so I can't convert them.
I usually use my file manager to link my webtoons from the drive to Kotatsu.
But this is impossible as they are pdf's.
Is it possible to add the pdf's to the application?
Thanks for your help.

**Comment by nv95** [comment]
This application is comic reader with a focus on online content, not a pdf or e-book reader. Pdf viewer mismatch main goals and will bloat this app. So, answer is _no_
