### ISSUE TITLE
Not enough options

### ISSUE THREAD

**Issue by Sairsey** [nv95/Kotatsu#5]
Hello! I started to use your application after OpenManga closed and I think your app is awesome, but I have questions about interface.
1) Can I get a list with only new chapters? If I can, how I must do it?
2) How I can mark chapters as 'read'? This numbers are irritating.
Maybe you should make instruction or FAQ?  I think I am not the first one with this question.

**Comment by nv95** [comment]
1 - no way. I will implement it later
2 - already fixed, coming soon in next release
