### ISSUE TITLE
Add MangaDex to its sources?

### ISSUE THREAD

**Issue by cheesuscrisp** [nv95/Kotatsu#51]
A lot of people (me included) use mangadex as our primary manga source, so was wondering if it could be added here.

**Comment by yant0** [comment]
#6

**Comment by yephny** [comment]
A single screenshot can describe this issue well. Here's a page out of arguably the most well-known manga of all time, Berserk:
![low](https://a.pomf.cat/qogvmp.png)

This is extremely low quality. Other English sources available in the app are no better. MangaDex should definitely be added.

**Comment by nv95** [comment]
I planned to add MangaDex in next major release

**Comment by nv95** [comment]
MangaDex is available in current release
