### ISSUE TITLE
"trying to reach a website

### ISSUE THREAD

**Issue by MountainsFury** [nv95/Kotatsu#54]
For some time now, i'm trying to access a website but for some reason im perceived as a bot( or so i believe it to be)

Trying to access the webstie from my home computer i get the errorr 402.
i checked the internet for soultions and this is what i tried so far:
-clear cookies
-clear browser cache
-shufled DNS cache
-restarted IP via cmd
-tried TOR browser VPN(got error 1020 this time)
-trying to access affiliated websites i got error 1020 no matter what browser i used
-tried to contact website administration and was ignored
-tried to open the link for that website via google translate and it worked to some extent(couldn't load images)
-tried to alternate from http to https etc.

in the end tried to acces this website from my work and it had no problems.

i'd like to ask if you have any idea what might be the problem and how solve it, thank you.

website link "mangalib.me"

**Comment by ztimms73** [comment]
I don't know much about this, but apparently rebooting the router will help you (this will change your IP address, unless of course it is static), VPN or proxy. That's all I can do to help you. Maybe there is a person who knows more about this. And yes, there are a lot of sources, you don't need to focus only on MangaLib.

**Comment by ztimms73** [comment]
Open new issue if the problem appears again
