### ISSUE TITLE
MangaRead Parser is Broken

### ISSUE THREAD

**Issue by XeroOl** [nv95/Kotatsu#58]
I'm getting the message "Cannot obtain manga id" when looking at a mangaread manga.

**Comment by ztimms73** [comment]
Mangaread site is currently broken. Wait patiently for it to be fixed or migrate to another source.

**Comment by XeroOl** [comment]
The site is no longer down, so it should be possible to see the parser bug now

**Comment by XeroOl** [comment]
I'm not sure if the site layout changed, but it looks like the field is now called `data-post` instead of `data-postid`
