### ISSUE TITLE
MangaDex not Showing up as a source

### ISSUE THREAD

**Issue by BrokenGale** [nv95/Kotatsu#6]
I just updated to the newest version 0.3.2 and it had Mangadex as a source. But I could not find mangadex when trying to add sources.

Still thank you for adding mangatown english source. I really appreciate it.

**Comment by nv95** [comment]
Oh, sorry. I tried to add mangadex but it has some features that are difficult to implement, so I discard mangadex for now. Maybe I will add it in the future.

**Comment by BrokenGale** [comment]
I do understand that Mangadex has a very difficult to implement interface. Thank you for trying though.
