### ISSUE TITLE
Anibel source changes

### ISSUE THREAD

**Issue by belarusaed** [nv95/Kotatsu#62]
Hello, recently anibel.net was updated, and now parser works only with old.anibel.net URL. It would be great to set it by default.

Also if you interested in, Anibel now have API: you can find GraphQL playground and automatically generated docs at [api-beta.anibel.net/graphql](https://api-beta.anibel.net/graphql).
But in production you should use api.anibel.net, because beta instances shutting down when not in use and it's working with actual production DB.

**Comment by ztimms73** [comment]
Hello, thank you for the information!

**Comment by ztimms73** [comment]
@belarusaed, вы из администрации сайта? Если да, то когда старая версия сайта перестанет функционировать?

**Comment by belarusaed** [comment]
@ztimms73 Не из администрации непосредственно; Как только функциональность старого сайта будет целиком перенесена, каких-то определенных сроков пока нету, но админ говорит, что будет не раньше, чем через месяца три.

**Comment by nv95** [comment]
I`m working on it

**Comment by belarusaed** [comment]
old.anibel.net already closed.

**Comment by ztimms73** [comment]
Я думаю пока можно парсить контент с помощью jsoup, а потом, как появятся силы и время, перейти на API

**Comment by nv95** [comment]
Done

**Comment by belarusaed** [comment]
request URL should be `api.anibel.net/graphql`, not just `api.anibel.net`.

P.S. Also posters are not loaded, but it's API problem that will be fixed in the future.

**Comment by belarusaed** [comment]
And I think it isn't a good idea to hardcode api subdomain. Maybe better whole api.anibel.net domain should be customizable, not only anibel.net?
