### ISSUE TITLE
Webtoon Style Scrolling Still has quite wide black bars

### ISSUE THREAD

**Issue by BrokenGale** [nv95/Kotatsu#7]
Webtoon style scrolling has quite wide black bars between individual pictures.
This behaviour is exhibited on the first 4 chapters of the Legendary Moonlight Sculptor on the MangaTown Source.
Possibly because the first page is not the same height as the rest of the chapter.

**Comment by BrokenGale** [comment]
After v0.4 update some black bars still exist. Especially the aforementioned chapters of legendary moonlight sculptor.
Test Device: LG V20 US996
Android Version: 8.0 Oreo (Latest Manufacturer provided version)

**Comment by nv95** [comment]
If page height is smaller than screen height you got padding on top and bottom, and, I think, it is ok. Usually webtoon page height is larger.
It is because it will be difficult to manage scroll if we can got more than 2 pages on screen in the same time

**Comment by BrokenGale** [comment]
The app is built around a very seamless experience for reading, padding kind of takes away from that experience. That is just an opinion however, if your goals include the padding, it shouldn't matter. Personally, removing the padding would make some mangas easier to read and smooth the experience out for all sized phone screens, especially for webtoon pages that are less than 1 screen in length.

**Comment by nv95** [comment]
@BrokenGale can you provide any screenshots?

**Comment by Zehra** [comment]
I've encountered this issue as well.
(Three screenshots provided with minor comments on each.)
Application version: **1.0.1.**

Large, but not highly noticeable spacing/gap.
![large-bar-2](https://user-images.githubusercontent.com/22282963/123357497-9b477080-d537-11eb-8293-14f91b889213.jpg)
Highly noticeable space/bar in images.
![large-bar](https://user-images.githubusercontent.com/22282963/123357508-a00c2480-d537-11eb-9b5f-630a71166690.jpg)
Smaller gap, but highly noticeable.
![small-bar](https://user-images.githubusercontent.com/22282963/123357533-aa2e2300-d537-11eb-8c2a-274f94f57a2c.jpg)

**Comment by nv95** [comment]
@Zehra thanks for details. What manga and source?

**Comment by Zehra** [comment]
@nv95 
The source is **MangaTown** and the series are **Peerless Alchemist** and **The Beginning After the End**.
(First two screenshots are from "Peerless Alchemist" and the third is of "The Beginning After the End".)

I've included a screenshot of the covers from series provided below:
![series-covers](https://user-images.githubusercontent.com/22282963/123476740-1b6ae600-d5cb-11eb-9bed-34d2f602dcce.jpg)
