### ISSUE TITLE
Feature Request: Custom save location for downloaded pages

### ISSUE THREAD

**Issue by yephny** [nv95/Kotatsu#70]
Kotatsu downloads saved pages to the Pictures folder automatically. I'd like it to download and keep them in a different folder.

**Comment by yephny** [comment]
If this is hard to implement, then at least create a directory in Pictures named Kotatsu and save the images there.

**Comment by nv95** [comment]
Ok

**Comment by yephny** [comment]
It looks like Kotatsu now saves in Pictures/Kotatsu, which is why I closed the issue.
