### ISSUE TITLE
[Feature request] Improving the display of the list of sources

### ISSUE THREAD

**Issue by ztimms73** [nv95/Kotatsu#78]
RU: Так как скоро могут быть в приложении такие источники, как MangaDex и Bato.to, а они поддерживают достаточно много языков, то я хочу представить идею, как улучшить список источников и их выбор. Без этого бы наверное список был бы перегружен одинаковыми названиями источников, только изменяется язык контента в названии. Можно кстати это применить в `NavigationView` (наверное кастомном, либо использовать библиотеку [MaterialDrawer](https://github.com/mikepenz/MaterialDrawer), как раз там collapsable items поддерживаются)
EN: Since MangaDex and Bato.to can appear soon and they support quite a lot of languages, then I want to present an idea on how to improve the list of sources and their selection. Without this, the list would probably be overloaded with the same source names, only the language of the content in the title changes. By the way, you can apply this in `NavigationView` (probably custom, or use the [MaterialDrawer](https://github.com/mikepenz/MaterialDrawer) library)
![Untitled](https://user-images.githubusercontent.com/61558546/146287398-32601192-5b51-458d-bc22-fe94c3510835.png)

**Comment by nv95** [comment]
Maybe it should be better to group the sources by language

**Comment by nv95** [comment]
But the main issue is sorting: how to allow the user to sort the sources if they are grouped?

**Comment by ztimms73** [comment]
> Maybe it should be better to group the sources by language

Like how is it made in Tachiyomi?
<img src="https://user-images.githubusercontent.com/61558546/148560208-00a57bf0-3dc5-404f-9cd5-c49995f93b4c.png" width=400>

> But the main issue is sorting: how to allow the user to sort the sources if they are grouped?

Hmm, well, yes, we need to think about it. Let's put it off for now until better times

**Comment by nv95** [comment]
![Screenshot_20220107-184817](https://user-images.githubusercontent.com/8948226/148579894-f61856c7-da29-4b62-a2c9-4fd5488c0f6e.png)

Ok, I implement it in another way

**Comment by ztimms73** [comment]
So cool!

**Comment by ztimms73** [comment]
Implemented. Thanks!
