### ISSUE TITLE
Где imageViewCover?

### ISSUE THREAD

**Issue by nknodev** [nv95/Kotatsu#79]
list\ui\adapter\MangaListItemAD.kt
Выдает ошибку, не может найти imageViewCover

**Comment by nv95** [comment]
Какая версия Android studio?

**Comment by ParTy-Play-go** [comment]
Последняя, Arctic Fox

**Comment by nv95** [comment]
У меня Chipmunk, у @Xtimms вроде тоже нормально собирается

**Comment by ParTy-Play-go** [comment]
Ок, попробую поставить ее, но все же, что за папка WebToon?

**Comment by ParTy-Play-go** [comment]
Ошибки выдаются
Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public inline fun ImageView.newImageRequest(url: String): ImageRequest.Builder defined in org.nkno.yumu.utils.ext in file CoilExt.kt

Unresolved reference: setChips

Пытался собрать на Chipmunk

**Comment by nv95** [comment]
> org.nkno.yumu.utils.ext

Что-то с пакетами и импортами)

**Comment by ParTy-Play-go** [comment]
Не, это я модификацию делаю, пакеты менял для удобства

**Comment by nv95** [comment]
А оригинальный проект без модификаций собирается?

**Comment by ParTy-Play-go** [comment]
> А оригинальный проект без модификаций собирается?

неа(

**Comment by ParTy-Play-go** [comment]
я в принципе в модификации обновлял зависимости

**Comment by ParTy-Play-go** [comment]
а где решение-то?

**Comment by nv95** [comment]
До сих пор актуально?
В голову приходят следующие стандартные варианты решения:
1. File -> Invalidate caches
2. Заново склонировать проект

**Comment by ParTy-Play-go** [comment]
> До сих пор актуально? В голову приходят следующие стандартные варианты решения:
> 
> 1. File -> Invalidate caches
> 2. Заново склонировать проект
не сработало(

**Comment by ztimms73** [comment]
Можно более подробные сведения, которые выдаются при сборке проекта? Только выбивает ошибку `Unresolved reference` или может быть что-то другое сейчас?
