### ISSUE TITLE
Widget malfunction

### ISSUE THREAD

**Issue by Th3R0w** [nv95/Kotatsu#86]
Hi, i used the widget on android ( currently using a samsung galaxy s21 ultra ). Every time i want to open a manga using the widget they told me that it "cannot find the manga" and pulls me back in the app. 

If you can make it work it will be awesome ! Thanks !

**Comment by nv95** [comment]
What widget are you having an issue with? History, favourites or both?

**Comment by Th3R0w** [comment]
Hi,

I'm having an issue with both widget.

So for the "recently mangas"

   - only the first one is clickable ( nothing happened when i click on the
   second one or else ) and it shows the error " an error as occurred : cannot
   find the manga.
   - I opted for the extended version so 1 row and 4 columns ( see photo )

For the library version it's the same, they are clickable but it doesn't
send me to the link in the application.

I think the video will help you understand the problem.

Also sometimes there is a problem with some mangas like dr.stone : there is
sometimes three same pages in a row.
Thanks anyway for your app, it's been great !
