### ISSUE TITLE
MangaRead invalid key issue

### ISSUE THREAD

**Issue by XeroOl** [nv95/Kotatsu#87]
When trying to read a page from any manga from MangaRead, it gives this error instead.

![Screenshot_20220119-015353](https://user-images.githubusercontent.com/6820998/150087725-c2737511-ef6d-4a83-a6fa-3f9cce8a244a.png)

```
invalid key value: ''
```

The image is from Dr. Stone, but any manga from the source MangaRead has this issue.

**Comment by nv95** [comment]
What version are you use? I think it already fixed in e56c61d834d3e584e0fc1321ea13976ec676ea9b

**Comment by nv95** [comment]
Oh, looks like it breaks again. Will fix it asap

**Comment by XeroOl** [comment]
if it helps, I am on 2.1.1 from F Droid

**Comment by XeroOl** [comment]
Still present in 2.1.2 from F Droid

**Comment by Dizzy49** [comment]
I also get the error when Saving

**Comment by XeroOl** [comment]
Working in 2.1.3, which has been released on F Droid!
Thank you very much!
