### ISSUE TITLE
Indicator that a Chapter has been Saved

### ISSUE THREAD

**Issue by Dizzy49** [nv95/Kotatsu#95]
Currently there does not appear to be any way to tell if a particular chapter has been downloaded or not.  Maybe change the grey box with the number to green if it's saved.

**Comment by nv95** [comment]
Available in #130

**Comment by shull49** [comment]
When/Where will the latest version be available?  F-Droid still only has 2.1.5

**Comment by ztimms73** [comment]
@shull49 check discussion #130

**Comment by nv95** [comment]
v3.0 is not so stable yet, you can wait until it becomes available in f-droid
