### ISSUE TITLE
Download Location Oddities

### ISSUE THREAD

**Issue by Dizzy49** [nv95/Kotatsu#99]
I've been fighting with the app trying to download about 10 manga, all from MangaTown.
I downloaded 6 to the shared internal location.  Then somehow the download Location was changed to Other location.  I tried to download a couple more and i got an error that the folder wasnt empty.

I checked the folder /Android/data/org...kotatsu/files/manga and I see the folders for those two manga, but they don't show up in the Local Storage.  Additionally, the other 6 that do appear in Local Storage are not in that folder.  There is one that is in the folder and in the Local Storage area. 

I cannot figure out how to get to the Other storage area

using V 2.1.3 from fdroid

on another note, where can i make some suggestions?

**Comment by nv95** [comment]
Folders for manga are temporary, downloaded manga stored in cbz files. You can simply remove them. Looks like a bug

**Comment by Dizzy49** [comment]
I'm still at a loss of where the other files are stored.  I'm reading a
manga that appears in my Local Storage area of the app, but does not appear
in the directory.
The tablet currently has no data services, so it's not connecting to
anything to read.
How can I get to that other directory?
